"""
HTML 输出构建模块
将 ECharts option 嵌入完整的独立 HTML 文件中
"""

import json

HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"><\\/script>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      display: flex; justify-content: center; align-items: center;
      min-height: 100vh; background: #f7f6f3;
      font-family: "PingFang SC", "Microsoft YaHei", "Hiragino Sans GB", sans-serif;
      padding: 20px;
    }}
    .chart-wrapper {{
      width: 960px; max-width: 96vw; height: 580px;
      background: #fff; border-radius: 14px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 8px 32px rgba(0,0,0,0.05);
      padding: 24px; border: 1px solid #e6e4e0;
    }}
    #chart {{ width: 100%; height: 100%; }}
    .footer {{
      position: fixed; bottom: 16px; left: 50%%; transform: translateX(-50%%);
      font-size: 11px; color: #ccc;
    }}
  </style>
</head>
<body>
  <div class="chart-wrapper">
    <div id="chart"></div>
  </div>
  <div class="footer">Generated by Chart Generator</div>
  <script>
    (function() {{
      var chart = echarts.init(document.getElementById('chart'));
      var option = {option_json};
      // 恢复渐变色（JSON 序列化会丢失）
      try {{
        var s = option.series;
        if (s && s.length > 0) {{
          for (var i = 0; i < s.length; i++) {{
            if (s[i].type === 'bar') {{
              s[i].itemStyle = s[i].itemStyle || {{}};
              if (!s[i].itemStyle.color) {{
                s[i].itemStyle.color = new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                  {{ offset: 0, color: '#9bbac8' }},
                  {{ offset: 1, color: '#8aa4b0' }}
                ]);
              }}
            }}
            if (s[i].type === 'line' && s[i].areaStyle) {{
              s[i].areaStyle.color = new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                {{ offset: 0, color: 'rgba(138,164,176,0.22)' }},
                {{ offset: 1, color: 'rgba(138,164,176,0.02)' }}
              ]);
            }}
          }}
        }}
      }} catch(e) {{}}
      chart.setOption(option);
      window.addEventListener('resize', function() {{ chart.resize(); }});
    }})();
  <\\/script>
</body>
</html>'''


def build_chart_html(option: dict, title: str = '图表') -> str:
    """
    根据 ECharts option 构建完整的独立 HTML 文件

    参数:
    option: ECharts option 字典
    title: 页面标题
    """
    # 格式化 option JSON，确保中文不转义
    option_json = json.dumps(option, ensure_ascii=False, indent=2)

    html = HTML_TEMPLATE.format(
        title=escape_html(title),
        option_json=option_json,
    )
    return html


def escape_html(text: str) -> str:
    """转义 HTML 特殊字符"""
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
            .replace("'", '&#39;'))
